placeholder_area = [
    {'teknisi': 18, 'service_area': 'BOGOR', 'sto': 'BOO'},
    {'teknisi': 3, 'service_area': 'CIAPUS - PAGELARAN', 'sto': 'CPS'},
    {'teknisi': 7, 'service_area': 'CIAPUS - PAGELARAN', 'sto': 'PAG'},
    {'teknisi': 3, 'service_area': 'CIAWI - CISARUA', 'sto': 'CJU'},
    {'teknisi': 9, 'service_area': 'CIAWI - CISARUA', 'sto': 'CRI'},
    {'teknisi': 10, 'service_area': 'CIAWI - CISARUA', 'sto': 'CSR'},
    {'teknisi': 11, 'service_area': 'CIAWI - CISARUA', 'sto': 'CWI'},
    {'teknisi': 4, 'service_area': 'CIBINONG', 'sto': 'BJD'},
    {'teknisi': 14, 'service_area': 'CIBINONG', 'sto': 'CBI'},
    {'teknisi': 2, 'service_area': 'CIBINONG', 'sto': 'TJH'},
    {'teknisi': 2, 'service_area': 'CILEUNGSI', 'sto': 'CAU'},
    {'teknisi': 11, 'service_area': 'CILEUNGSI', 'sto': 'CLS'},
    {'teknisi': 2, 'service_area': 'CILEUNGSI', 'sto': 'JGL'},
    {'teknisi': 5, 'service_area': 'CINERE', 'sto': 'CNE'},
    {'teknisi': 6, 'service_area': 'CINERE', 'sto': 'PCM'},
    {'teknisi': 17, 'service_area': 'DEPOK', 'sto': 'DEP'},
    {'teknisi': 2, 'service_area': 'DRAMAGA', 'sto': 'CGD'},
    {'teknisi': 9, 'service_area': 'DRAMAGA', 'sto': 'DMG'},
    {'teknisi': 1, 'service_area': 'DRAMAGA', 'sto': 'JSA'},
    {'teknisi': 1, 'service_area': 'DRAMAGA', 'sto': 'LBI'},
    {'teknisi': 9, 'service_area': 'DRAMAGA', 'sto': 'LWL'},
    {'teknisi': 5, 'service_area': 'GUNUNG PUTRI - CIANGSANA', 'sto': 'CSN'},
    {'teknisi': 3, 'service_area': 'GUNUNG PUTRI - CIANGSANA', 'sto': 'GPI'},
    {'teknisi': 8, 'service_area': 'KEDUNG HALANG', 'sto': 'KHL'},
    {'teknisi': 2, 'service_area': 'PARUNG - SEMPLAK', 'sto': 'CSE'},
    {'teknisi': 4, 'service_area': 'PARUNG - SEMPLAK', 'sto': 'PAR'},
    {'teknisi': 12, 'service_area': 'PARUNG - SEMPLAK', 'sto': 'SPL'},
    {'teknisi': 3, 'service_area': 'PASIR MAUNG', 'sto': 'CTR'},
    {'teknisi': 2, 'service_area': 'PASIR MAUNG', 'sto': 'PMU'},
    {'teknisi': 2, 'service_area': 'PASIR MAUNG', 'sto': 'STL'},
    {'teknisi': 18, 'service_area': 'SUKMAJAYA', 'sto': 'CSL'},
    {'teknisi': 5, 'service_area': 'SUKMAJAYA', 'sto': 'SKJ'},
    {'teknisi': 1, 'service_area': 'CIBADAK', 'sto': 'BGL'},
    {'teknisi': 9, 'service_area': 'CIBADAK', 'sto': 'CBD'},
    {'teknisi': 5, 'service_area': 'CIBADAK', 'sto': 'CCR'},
    {'teknisi': 2, 'service_area': 'CIBADAK', 'sto': 'CKB'},
    {'teknisi': 4, 'service_area': 'CIBADAK', 'sto': 'JPK'},
    {'teknisi': 1, 'service_area': 'CIBADAK', 'sto': 'KLU'},
    {'teknisi': 6, 'service_area': 'CIBADAK', 'sto': 'PLR'},
    {'teknisi': 5, 'service_area': 'SUKABUMI', 'sto': 'CMO'},
    {'teknisi': 1, 'service_area': 'SUKABUMI', 'sto': 'NLD'},
    {'teknisi': 2, 'service_area': 'SUKABUMI', 'sto': 'SGN'},
    {'teknisi': 23, 'service_area': 'SUKABUMI', 'sto': 'SKB'}
]
